In [131]:
import pandas
import numpy as np
import matplotlib.pyplot as plt



def dataset(mode): #mode取weather或air
    root = '/home/lifuzhen/KDD2018/'+mode+'.csv'
    data = pandas.read_csv(root)
    return data


mode = 'beijing_17_18_aq' #air day Figure
air = dataset(mode)
# print(air.describe())

gap_air = 24

PM10_miss = []
PM10_inter = []
index = 0
count = 0
for value in air['PM10']:

    if np.isnan(value):
        count += 1
        
    elif count != 0:
        PM10_miss.append(count)
        
        if count >= gap_air:
            PM10_inter.append(index - count)
            PM10_inter.append(index)
            
        count = 0
        
    index += 1

PM25_miss = []
PM25_inter = []
index = 0
count = 0
for value in air['PM2.5']:

    if np.isnan(value):
        count += 1
        
    elif count != 0:
        PM25_miss.append(count)
        
        if count >= gap_air:
            PM25_inter.append(index - count)
            PM25_inter.append(index)
            
        count = 0
        
    index += 1
    
NO2_miss = []
NO2_inter = []
index = 0
count = 0
for value in air['NO2']:

    if np.isnan(value):
        count += 1
        
    elif count != 0:
        NO2_miss.append(count)
        
        if count >= gap_air:
            NO2_inter.append(index - count)
            NO2_inter.append(index)
            
        count = 0
        
    index += 1

CO_miss = []
CO_inter = []
index = 0
count = 0
for value in air['CO']:

    if np.isnan(value):
        count += 1
        
    elif count != 0:
        CO_miss.append(count)
        
        if count >= gap_air:
            CO_inter.append(index - count)
            CO_inter.append(index)
            
        count = 0
        
    index += 1
    
O3_miss = []
O3_inter = []
index = 0
count = 0
for value in air['O3']:

    if np.isnan(value):
        count += 1
        
    elif count != 0:
        O3_miss.append(count)
        
        if count >= gap_air:
            O3_inter.append(index - count)
            O3_inter.append(index)
            
        count = 0
        
    index += 1
    
SO2_miss = []
SO2_inter = []
index = 0
count = 0
for value in air['SO2']:

    if np.isnan(value):
        count += 1
        
    elif count != 0:
        SO2_miss.append(count)
        
        if count >= gap_air:
            SO2_inter.append(index - count)
            SO2_inter.append(index)
            
        count = 0
        
    index += 1
    
PM10_inter.append(309327)
PM25_inter.append(309327)
NO2_inter.append(309327)
CO_inter.append(309327)
O3_inter.append(309327)
SO2_inter.append(309327)
print(max(PM10_miss))
print(PM10_inter)

2100
[17, 42, 94, 185, 987, 1033, 1763, 1827, 6059, 6105, 6304, 6398, 6461, 6552, 6760, 6795, 9014, 9039, 10586, 10611, 10876, 10992, 14947, 14978, 17774, 17812, 17852, 17933, 18121, 18153, 18758, 18808, 18902, 18944, 19475, 19507, 19534, 19592, 19874, 19907, 20294, 20322, 22520, 22581, 22844, 22869, 23852, 23882, 24076, 24121, 24259, 24314, 24532, 24567, 32758, 32792, 32962, 32994, 35630, 35704, 36088, 36115, 36537, 36583, 36686, 36717, 37222, 37268, 37303, 37362, 40617, 40644, 41606, 41643, 41848, 41881, 41883, 41931, 42028, 42056, 42057, 42094, 42299, 42336, 43610, 43648, 44430, 44520, 44537, 44605, 44753, 44804, 44954, 45010, 45011, 45049, 45087, 45117, 45146, 45230, 45256, 45287, 45375, 45472, 45574, 45615, 45664, 45721, 45851, 45875, 46055, 46092, 46093, 46163, 46182, 46219, 46220, 46272, 46335, 46361, 46498, 46535, 47632, 47667, 48024, 48059, 48250, 48274, 48475, 48501, 48522, 48557, 48610, 48640, 49166, 49222, 49415, 49441, 49701, 49863, 49985, 50065, 50409, 50444, 50472, 50538, 50731, 50792, 50891, 50967, 51158, 51193, 51209, 51235, 51268, 51293, 51341, 51425, 51822, 51851, 52480, 52546, 52876, 52903, 53195, 53225, 53461, 53500, 54012, 54038, 55102, 55138, 55791, 55819, 58495, 58536, 59394, 59440, 59637, 59678, 59796, 59831, 59832, 59868, 62286, 62388, 62741, 62773, 62950, 62996, 63187, 63236, 63351, 63386, 63966, 64032, 64251, 64279, 65322, 67175, 67389, 67421, 67997, 68110, 71171, 71259, 72049, 72083, 72851, 72907, 77148, 77199, 77389, 77441, 78291, 78317, 80059, 80136, 80984, 81008, 81737, 81793, 83874, 83898, 86052, 86083, 86278, 86313, 86314, 86350, 86482, 86521, 88978, 89004, 90624, 90682, 94943, 94971, 95164, 95209, 95212, 95238, 95368, 95412, 97832, 97904, 99452, 99477, 99509, 99565, 101176, 101218, 103822, 103850, 104049, 104085, 104086, 104124, 104217, 104298, 105813, 105853, 106188, 106222, 106982, 107011, 107629, 107663, 108415, 108452, 109109, 109136, 111386, 111416, 112026, 112060, 112697, 112731, 113117, 113187, 115083, 115107, 115595, 115712, 116063, 116090, 116273, 116300, 116661, 116702, 117279, 117344, 117959, 117993, 118621, 120721, 120792, 120831, 121592, 121619, 121818, 121854, 123265, 123289, 124419, 124445, 124559, 124590, 125395, 125437, 126108, 126135, 126165, 126223, 130707, 130743, 130758, 130791, 130868, 130955, 131161, 131199, 134287, 134323, 134436, 134466, 135072, 135109, 135247, 135276, 136872, 136915, 137311, 137402, 137559, 137584, 137814, 137845, 139353, 139402, 139595, 139630, 139775, 139834, 141378, 141406, 142198, 142222, 142261, 142340, 142525, 142554, 142696, 142754, 142910, 142960, 143156, 143210, 143316, 143347, 143458, 143658, 143844, 143903, 143941, 143978, 143981, 144007, 144009, 144110, 144246, 144282, 145378, 145416, 145705, 145729, 145768, 145794, 148229, 148288, 148476, 148567, 148636, 148728, 148932, 148971, 151168, 151223, 151224, 151251, 151607, 151633, 151801, 151845, 152050, 152096, 152211, 152235, 152726, 152761, 152825, 152861, 154320, 154473, 155123, 156996, 160075, 160133, 161731, 161774, 164479, 164573, 166011, 166060, 166253, 166297, 166312, 166342, 166418, 166456, 166457, 166500, 167669, 167723, 169833, 169874, 169979, 170004, 170534, 170558, 170616, 170653, 175139, 175184, 175188, 175221, 175318, 175343, 175344, 175384, 175594, 175627, 177738, 177763, 177764, 177810, 177853, 177928, 178693, 178754, 178868, 178904, 179422, 179447, 179510, 179547, 179788, 179819, 180924, 180962, 183775, 183844, 184026, 184071, 184072, 184115, 184191, 184273, 185783, 185845, 186606, 186656, 186688, 186768, 186952, 187011, 187143, 187177, 187339, 187406, 187580, 187641, 187755, 187779, 188312, 188338, 188370, 188430, 191469, 191500, 191786, 191827, 192665, 192713, 192910, 193004, 193075, 193158, 193366, 193400, 195599, 195679, 196251, 196284, 196479, 196525, 196635, 196672, 197195, 197219, 197277, 197318, 197570, 197599, 199540, 199574, 199591, 199620, 200864, 200908, 201551, 201583, 201803, 201831, 203561, 203600, 204736, 204781, 206162, 206197, 210457, 210490, 210683, 210717, 210887, 210928, 213282, 213309, 213347, 213447, 213809, 213836, 214249, 214297, 214413, 214439, 215053, 215091, 215331, 215371, 217205, 218115, 218130, 218247, 219571, 219614, 222232, 222256, 222257, 222294, 223158, 223185, 223855, 223882, 223913, 223978, 225695, 225721, 227541, 227574, 228454, 228480, 228658, 228700, 230182, 230257, 230590, 230620, 231152, 231197, 231386, 231415, 231792, 231827, 232025, 232069, 232819, 232862, 234630, 234658, 235150, 235178, 236223, 236251, 237123, 237147, 237341, 237375, 237545, 237586, 239922, 239971, 239973, 240002, 240005, 240076, 240277, 240316, 240462, 240493, 240666, 240715, 240907, 240956, 241065, 241095, 241587, 241626, 241627, 241743, 243298, 243324, 245996, 246033, 246225, 246271, 246287, 246318, 246391, 246436, 246437, 246474, 247240, 247264, 248889, 248963, 249354, 249380, 249800, 249847, 250569, 250625, 252630, 252706, 253553, 253578, 253634, 253675, 253701, 253740, 253748, 253781, 253959, 253996, 254008, 254051, 254059, 254091, 254864, 254917, 255113, 255139, 255302, 255334, 257828, 257854, 258467, 258493, 258669, 258693, 258694, 258727, 258843, 258868, 259483, 259513, 259760, 259796, 261778, 261810, 263773, 263805, 263999, 264024, 264203, 264242, 266136, 266163, 266592, 266633, 266647, 266770, 266927, 266974, 267109, 267151, 267239, 267266, 267314, 267380, 267553, 267614, 267723, 267761, 268227, 268285, 268343, 268379, 268380, 268405, 268646, 268692, 269418, 269562, 271769, 271802, 272063, 272087, 272639, 272700, 272883, 272936, 273054, 273087, 273088, 273132, 273337, 273373, 274208, 274232, 274638, 274663, 275344, 275372, 275485, 275540, 275542, 275664, 275677, 275717, 275748, 275871, 275972, 276038, 276039, 276087, 276100, 276145, 276173, 276260, 276294, 276321, 276389, 276500, 276534, 276575, 276603, 276651, 276657, 276684, 277090, 277167, 277240, 277294, 277533, 277574, 278544, 278703, 279056, 279103, 279466, 279513, 279515, 279582, 279586, 279624, 279625, 279688, 279838, 279895, 280072, 280097, 280220, 280254, 281530, 281561, 283142, 283168, 283910, 283943, 284480, 284517, 284891, 284924, 285097, 285123, 285337, 285372, 285495, 285537, 285755, 285779, 286007, 286052, 286111, 286172, 286414, 286452, 286655, 286702, 288235, 288301, 288490, 288552, 289306, 289333, 290407, 290472, 290645, 290719, 290720, 290748, 290792, 290819, 290838, 290904, 290987, 291058, 291063, 291335, 292424, 292480, 293317, 293395, 293396, 293422, 293783, 293815, 294234, 294272, 294387, 294411, 294998, 295085, 295305, 295341, 296828, 296852, 299342, 299371, 299540, 299577, 299747, 299782, 301314, 301347, 302208, 302303, 302666, 302695, 302758, 302804, 302877, 302914, 302940, 302964, 303101, 303156, 303273, 303298, 303792, 303828, 303883, 303944, 305324, 305353, 305708, 305791, 307071, 307111, 307200, 307224, 307523, 307548, 307897, 307944, 308176, 308220, 308426, 308463, 308465, 308504, 308585, 308673, 309327]

In [132]:
left = 0
copy_PM10 = air['PM10'].copy()
for i in range(len(PM10_inter)):
    right = PM10_inter[i]
    copy_PM10[left : right] = copy_PM10[left : right].interpolate()
    left = right

left = 0
copy_PM25 = air['PM2.5'].copy()
for i in range(len(PM25_inter)):
    right = PM25_inter[i]
    copy_PM25[left : right] = copy_PM25[left : right].interpolate()
    left = right

left = 0
copy_NO2 = air['NO2'].copy()
for i in range(len(NO2_inter)):
    right = NO2_inter[i]
    copy_NO2[left : right] = copy_NO2[left : right].interpolate()
    left = right
    
left = 0
copy_CO = air['CO'].copy()
for i in range(len(CO_inter)):
    right = CO_inter[i]
    copy_CO[left : right] = copy_CO[left : right].interpolate()
    left = right
    
left = 0
copy_O3 = air['O3'].copy()
for i in range(len(O3_inter)):
    right = O3_inter[i]
    copy_O3[left : right] = copy_O3[left : right].interpolate()
    left = right
    
left = 0
copy_SO2 = air['SO2'].copy()
for i in range(len(SO2_inter)):
    right = SO2_inter[i]
    copy_SO2[left : right] = copy_SO2[left : right].interpolate()
    left = right
    
# copy_PM10.head(50)

In [133]:
copy_air = air[['stationId','utc_time']]
copy_air = pandas.concat([copy_air,copy_PM25,copy_PM10,copy_NO2,copy_CO,copy_O3,copy_SO2], axis= 1)
copy_air.dropna(thresh=7,inplace=True)
copy_air.to_csv('/home/lifuzhen/KDD2018/copy_air.csv', index = True)
copy_air.describe()

,PM2.5,PM10,NO2,CO,O3,SO2
count,298912.000000,281685.000000,299305.000000,281540.000000,299147.000000,299115.000000
mean,58.755218,87.331969,45.670830,0.961500,55.778577,8.967459
std,66.293036,87.142088,32.088004,0.994652,53.854184,11.709873
min,2.000000,5.000000,1.000000,0.100000,1.000000,1.000000
25%,16.000000,36.000000,20.000000,0.400000,12.000000,2.000000
50%,39.000000,69.000000,39.000000,0.700000,45.000000,5.000000
75%,77.000000,113.000000,66.000000,1.200000,79.000000,11.000000
max,1004.000000,3000.000000,300.000000,15.000000,504.000000,307.000000